package workers

import (
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"
)

// FileStore writes uploaded documents under a single root directory. Paths
// recorded in the database are always RELATIVE to that root, so the volume can
// be remounted elsewhere without rewriting rows.
type FileStore struct {
	root     string
	maxBytes int64
}

func NewFileStore(root string, maxBytes int64) *FileStore {
	return &FileStore{root: root, maxBytes: maxBytes}
}

var ErrFileTooLarge = errors.New("file too large")
var ErrUnsupportedType = errors.New("unsupported file type")

// allowedExtensions is an allow-list rather than a deny-list: these are the
// formats a scanned or exported certificate actually arrives in. Anything
// executable or scriptable is absent by construction.
var allowedExtensions = map[string]string{
	".pdf":  "application/pdf",
	".jpg":  "image/jpeg",
	".jpeg": "image/jpeg",
	".png":  "image/png",
	".webp": "image/webp",
	".heic": "image/heic",
	".gif":  "image/gif",
	".doc":  "application/msword",
	".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".odt":  "application/vnd.oasis.opendocument.text",
}

// Save streams src to disk and returns the path relative to the store root.
//
// The stored name is a fresh UUID plus the validated extension — the client's
// filename is never used to build a path, which removes directory traversal as
// a category rather than trying to sanitise it. The original name is kept only
// as a database column, for display.
func (fs *FileStore) Save(src io.Reader, originalName string) (relPath, contentType string, size int64, err error) {
	ext := strings.ToLower(filepath.Ext(originalName))
	contentType, ok := allowedExtensions[ext]
	if !ok {
		return "", "", 0, fmt.Errorf("%w: %q", ErrUnsupportedType, ext)
	}

	now := time.Now().UTC()
	dir := filepath.Join("certifications", now.Format("2006"), now.Format("01"))
	if err := os.MkdirAll(filepath.Join(fs.root, dir), 0o750); err != nil {
		return "", "", 0, fmt.Errorf("create upload dir: %w", err)
	}

	relPath = filepath.Join(dir, uuid.NewString()+ext)
	abs := filepath.Join(fs.root, relPath)

	f, err := os.OpenFile(abs, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o640)
	if err != nil {
		return "", "", 0, fmt.Errorf("create upload file: %w", err)
	}
	defer f.Close()

	// LimitReader caps at maxBytes+1 so that hitting the cap exactly is
	// distinguishable from merely reaching it.
	written, err := io.Copy(f, io.LimitReader(src, fs.maxBytes+1))
	if err != nil {
		os.Remove(abs)
		return "", "", 0, fmt.Errorf("write upload: %w", err)
	}
	if written > fs.maxBytes {
		os.Remove(abs)
		return "", "", 0, ErrFileTooLarge
	}

	return relPath, contentType, written, nil
}

// Open resolves a stored relative path back to a readable file, refusing
// anything that escapes the root. Stored paths are generated by Save and so
// are already safe, but a corrupted or hand-edited row must not become an
// arbitrary-file-read primitive.
func (fs *FileStore) Open(relPath string) (*os.File, error) {
	if relPath == "" {
		return nil, os.ErrNotExist
	}
	root, err := filepath.Abs(fs.root)
	if err != nil {
		return nil, err
	}
	abs := filepath.Join(root, filepath.Clean("/"+relPath))
	if abs != root && !strings.HasPrefix(abs, root+string(os.PathSeparator)) {
		return nil, os.ErrNotExist
	}
	return os.Open(abs)
}

// Remove deletes a stored file. A missing file is not an error: the database
// row is the record of truth and cleanup runs after the row has already
// changed, so a half-finished earlier attempt must not block anything.
func (fs *FileStore) Remove(relPath string) error {
	if relPath == "" {
		return nil
	}
	root, err := filepath.Abs(fs.root)
	if err != nil {
		return err
	}
	abs := filepath.Join(root, filepath.Clean("/"+relPath))
	if abs != root && !strings.HasPrefix(abs, root+string(os.PathSeparator)) {
		return nil
	}
	if err := os.Remove(abs); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

// contentDisposition builds a Content-Disposition header that survives
// non-ASCII filenames — most of these are Cyrillic — while keeping a plain
// ASCII fallback for older clients.
func contentDisposition(name string) string {
	if name == "" {
		name = "certificate"
	}
	// Strip anything that could break out of the quoted string or inject a
	// header, then let mime handle the RFC 5987 encoding of the real name.
	ascii := strings.Map(func(r rune) rune {
		if r < 32 || r == '"' || r == '\\' || r == '\r' || r == '\n' || r > 126 {
			return '_'
		}
		return r
	}, name)
	// The quoted form is the fallback; filename* carries the real UTF-8 name.
	return fmt.Sprintf(`attachment; filename="%s"; filename*=UTF-8''%s`,
		ascii, url.PathEscape(name))
}
